(()=>{const K='ipa615',db=()=>{try{return JSON.parse(localStorage.getItem(K)||'{}')}catch{return{}}},save=x=>localStorage.setItem(K,JSON.stringify(x));
const modal=h=>{document.querySelector('.b615o')?.remove();let o=document.createElement('div');o.className='b615o';o.innerHTML='<div class="b615m"><button class="b615x">×</button>'+h+'</div>';document.body.appendChild(o);o.querySelector('.b615x').onclick=()=>o.remove();return o};
function rating(b){let key=b.dataset.journeyRate||'local',s=db(),cur=s.ratings?.[key]?.rating||0,o=modal(`<h2>Avaliar lugar</h2><p>Toque nas estrelas</p><div class="b615stars">${[1,2,3,4,5].map(n=>`<button data-s="${n}">★</button>`).join('')}</div><b class="b615score"></b><textarea placeholder="Comentário opcional"></textarea><button class="btn btn-primary b615save">Salvar avaliação</button>`),v=cur;
const paint=()=>{o.querySelectorAll('[data-s]').forEach(x=>x.classList.toggle('on',+x.dataset.s<=v));o.querySelector('.b615score').textContent=v?v+'/5':'Selecione uma nota'};
o.querySelectorAll('[data-s]').forEach(x=>{let f=e=>{e.preventDefault();e.stopPropagation();v=+x.dataset.s;paint()};x.addEventListener('pointerup',f);x.addEventListener('click',f)});paint();
o.querySelector('.b615save').onclick=()=>{if(!v)return alert('Selecione uma nota');s=db();s.ratings||={};s.ratings[key]={rating:v,note:o.querySelector('textarea').value,date:new Date().toISOString()};save(s);try{let p=key.split('|');if(window.IPAData?.saveJourneyPlace&&p.length>2)IPAData.saveJourneyPlace(p[0],p[1],p[2],s.ratings[key])}catch{}o.remove()} }
function moment(b){let key=b.dataset.moment,o=modal(`<h2>📷 Registrar momento</h2><p>Essa mídia alimentará Memórias, Álbum e Filme.</p><label class="b615up">Tirar foto / escolher da galeria<input type="file" accept="image/*,video/*" capture="environment" multiple></label><div class="b615prev"></div><input class="b615cap" placeholder="Legenda"><label><input class="b615fav" type="checkbox"> ❤️ Destaque da viagem</label><button class="btn btn-primary b615ms">Salvar momento</button>`),files=[];
o.querySelector('input[type=file]').onchange=e=>{files=[...e.target.files];let p=o.querySelector('.b615prev');p.innerHTML='';files.slice(0,6).forEach(f=>{let u=URL.createObjectURL(f),el=document.createElement(f.type.startsWith('video')?'video':'img');el.src=u;if(el.tagName==='VIDEO')el.controls=true;p.appendChild(el)})};
o.querySelector('.b615ms').onclick=()=>{if(!files.length)return alert('Escolha uma foto ou vídeo');let s=db();s.moments||=[];files.forEach(f=>s.moments.push({place:key,name:f.name,type:f.type,caption:o.querySelector('.b615cap').value,featured:o.querySelector('.b615fav').checked,date:new Date().toISOString()}));save(s);o.remove();alert('Momento registrado ✓')} }
function explore(){let o=modal(`<h2>✨ Explorar</h2><p>Dicas inteligentes fora do seu roteiro.</p><div class="b615filters"><button data-q="cafe">☕ Cafés</button><button data-q="restaurant">🍽️ Restaurantes</button><button data-q="bar">🍸 Bares</button><button data-q="shopping">🛍️ Compras</button><button data-q="tourist attraction">📸 Descobrir</button></div><div class="b615res">Escolha uma categoria.</div>`),r=o.querySelector('.b615res');
o.querySelectorAll('[data-q]').forEach(b=>b.onclick=async()=>{r.textContent='Buscando…';try{let x=await fetch('/api/places/recommend',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query:b.dataset.q})}),j=await x.json(),a=j.places||j.results||[];r.innerHTML=a.slice(0,8).map(p=>`<div class="b615rec"><b>${p.displayName?.text||p.name||'Sugestão'}</b><small>${p.formattedAddress||''}</small><button data-add="${p.displayName?.text||p.name||'Lugar'}">+ Adicionar à rota</button></div>`).join('')||'Nenhuma sugestão agora';r.querySelectorAll('[data-add]').forEach(x=>x.onclick=()=>{let s=db();s.routeAdds||=[];s.routeAdds.push(x.dataset.add);save(s);alert('Adicionado à rota pessoal ✓')})}catch{r.textContent='Não foi possível carregar as dicas.'}})}
function decorate(){document.querySelectorAll('[data-journey-rate]').forEach(b=>{if(!b.dataset.b615){b.dataset.b615='1';let m=document.createElement('button');m.type='button';m.className='b615moment';m.dataset.moment=b.dataset.journeyRate;m.textContent='📷 Momento';b.parentElement?.appendChild(m)}});[...document.querySelectorAll('button,a')].filter(x=>/^\s*explorar\s*$/i.test(x.textContent||'')).forEach(x=>x.dataset.b615explore='1')}
document.addEventListener('pointerup',e=>{let r=e.target.closest('[data-journey-rate]');if(r){e.preventDefault();e.stopImmediatePropagation();rating(r);return}let m=e.target.closest('.b615moment');if(m){e.preventDefault();e.stopImmediatePropagation();moment(m);return}let x=e.target.closest('[data-b615explore]');if(x){e.preventDefault();e.stopImmediatePropagation();explore()}},true);
new MutationObserver(decorate).observe(document.documentElement,{subtree:true,childList:true});addEventListener('DOMContentLoaded',decorate);window.IPABeta615={explore};})();